### ISSUE TITLE
`undefined local variable or method `hash_or_path' for Hubba:Module`

### ISSUE THREAD

**Issue by MrJoy** [rubycoco/git#2]
In `reposet.rb`:

```ruby
def self.update_stats( host_or_path='./repos.yml' )  ## move to reposet e.g. Reposet#update_status!!!!
  h = if hash_or_path.is_a?( String )    ## assume it is a file path!!!
        path = hash_or_path
        YAML.load_file( path )
      else
        hash_or_path  # assume its a hash / reposet already!!!
      end

  gh = Github.new
  gh.update_stats( h )
end
```

Note that the param is named `host_or_path`.

**Comment by geraldb** [comment]
Thanks for trying hubba and reporting the typo. You're right that should be `hash_or_path`.  I published an update / fix. Please, try the latest version v0.6.2.    If you still run into any trouble, please report back. Thanks. Greetings from Vienna, Austria. Cheers. Prost.

**Comment by MrJoy** [comment]
Much obliged!
